### ISSUE TITLE
Grafana dashboard is off compared to metrics

### ISSUE THREAD

**Issue by remimikalsen** [hnlq715/nginx-vts-exporter#74]
The problem:
This Grafana dashboard doesn't seem to be reporting right numbers for ServerBytes
 - https://grafana.com/dashboards/2949

My Grafana dashboard shows the following:
 - ServerBytes for the all hosts peak at 12.92KiB out
 - ServerBytes for the owncloud host peak at 4.1KiB out
 - The JSON-file and the nginx-vts-exporter metrics are accumulated numbers, but even so the grafana graph seems far off.

**http://nginx-vts-exporter:9913/metrics** contains, among other data, the following lines:
```
nginx_server_bytes{direction="in",host="my.owncloud.host"} 6.7403731e+07
nginx_server_bytes{direction="out",host="my.owncloud.host"} 6.8422731e+07
nginx_upstream_bytes{backend="172.22.0.7:8080",direction="in",upstream="my.owncloud.host"} 6.7403731e+07
nginx_upstream_bytes{backend="172.22.0.7:8080",direction="out",upstream="my.owncloud.host"} 6.8422731e+07
```
- I note that there are float64 numbers formatted in the scientific notation, wondering if that could be an issue when reading the value into Grafana
- I have cross checked the numbers, and they seem to add up when comparing with http://nginx-vts-status/status/format/json

My nginx-vts-exporter on **docker-compose.yml**:
```
    nginx-vts-exporter:
    container_name: nginx-vts-exporter
    image: sophos/nginx-vts-exporter
    restart: always
    networks:
      - backend
      - frontend
    environment:
      - TZ=Europe/Oslo
      - NGINX_STATUS=http://nginx-vts-status/status/format/json
```

From **prometheus.yml** scrape_configs (scrape interval 5 seconds):
```
    - job_name: 'nginx-vts-exporter:'
      static_configs:
        - targets: ['nginx-vts-exporter:9913']
```

The prometheus data source seems to be working well in Grafana; the node exporter f.ex. seems to report correctly.

Best Regards,
Remi
